name: CD for Cloud Run functions on Firebase

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    timeout-minutes: 15
    outputs:
      backend_functions: ${{ steps.filter.outputs.backend_functions }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend_functions:
              - 'backend/functions/**'

  deploy_functions:
    name: Deploy Functions
    needs:
      - changes
    if: ${{ needs.changes.outputs.backend_functions == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 60
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_FB }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_MAIL_FB }}
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: ./backend/functions

      - name: Deploy to Functions
        run: |
          npm install -g firebase-tools
          firebase deploy --only functions --force --project=${{ secrets.PROJECT_ID }}
        working-directory: ./backend/functions